# -*- coding: utf-8 -*-
"""funciones_analisis_aguas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Ru6hcOSGCjNHlTfOxRyvy1kpxAQpzUO
"""

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# 1. Carga del conjunto de datos oficial
df = pd.read_excel('dataset_set_A_aguas_residuales.xlsx')

# 2. Configuración estética general
sns.set_theme(style='whitegrid', palette='muted')
fig, axes = plt.subplots(2, 2, figsize=(15, 11))

# --- PANEL A: Dispersión de DBO de Salida con Umbral Normativo ---
sns.boxplot(
    data=df,
    x='planta',
    y='DBO_salida_mg_L',
    palette=['#3498DB', '#2980B9', '#1B4F72'],
    ax=axes[0, 0],
    width=0.45,
    fliersize=4,
)
axes[0, 0].axhline(
    30,
    color='#C0392B',
    linestyle='--',
    linewidth=2,
    label='Límite Regulatorio (30 mg/L)',
)
axes[0, 0].set_title(
    'A) Dispersión de DBO de Salida por Planta', fontsize=12, fontweight='bold'
)
axes[0, 0].set_xlabel('Planta de Tratamiento', fontweight='bold')
axes[0, 0].set_ylabel('DBO Salida (mg/L)', fontweight='bold')
axes[0, 0].legend(loc='upper right', frameon=True)

# --- PANEL B: Tasa de Cumplimiento Normativo (%) por Planta ---
tasa_cumpl = (
    df.groupby('planta')['cumplimiento_norma'].mean().reset_index()
)  # Proporción
tasa_cumpl['cumplimiento_pct'] = tasa_cumpl['cumplimiento_norma'] * 100
barplot = sns.barplot(
    data=tasa_cumpl,
    x='planta',
    y='cumplimiento_pct',
    palette=['#27AE60', '#2ECC71', '#58D68D'],
    ax=axes[0, 1],
    width=0.45,
)
axes[0, 1].set_title(
    'B) Tasa de Cumplimiento Normativo (%)', fontsize=12, fontweight='bold'
)
axes[0, 1].set_xlabel('Planta de Tratamiento', fontweight='bold')
axes[0, 1].set_ylabel('Cumplimiento (%)', fontweight='bold')
axes[0, 1].set_ylim(0, 40)
for p in axes[0, 1].patches:
  axes[0, 1].annotate(
      f'{p.get_height():.1f}%',
      (p.get_x() + p.get_width() / 2.0, p.get_height()),
      ha='center',
      va='baseline',
      fontsize=11,
      fontweight='bold',
      xytext=(0, 5),
      textcoords='offset points',
  )

# --- PANEL C: Caudal de Entrada vs DBO Salida y Cumplimiento ---
palette_cumpl = {0: '#E74C3C', 1: '#27AE60'}
sns.scatterplot(
    data=df,
    x='caudal_entrada_m3_d',
    y='DBO_salida_mg_L',
    hue='cumplimiento_norma',
    style='planta',
    s=85,
    alpha=0.85,
    palette=palette_cumpl,
    ax=axes[1, 0],
)
axes[1, 0].axhline(
    30,
    color='gray',
    linestyle=':',
    linewidth=1.2,
    label='Límite DBO (30 mg/L)',
)
axes[1, 0].set_title(
    'C) Caudal de Entrada vs. DBO de Salida', fontsize=12, fontweight='bold'
)
axes[1, 0].set_xlabel('Caudal de Entrada (m³/día)', fontweight='bold')
axes[1, 0].set_ylabel('DBO Salida (mg/L)', fontweight='bold')
handles, labels = axes[1, 0].get_legend_handles_labels()
# Mapeo de leyendas para reporte gerencial
labels_edit = [
    'Cumplimiento' if l == 'cumplimiento_norma' else l for l in labels
]
labels_edit = ['No Conforme (0)' if l == '0' else l for l in labels_edit]
labels_edit = ['Conforme (1)' if l == '1' else l for l in labels_edit]
axes[1, 0].legend(
    handles=handles,
    labels=labels_edit,
    title='Referencia',
    bbox_to_anchor=(1.02, 1),
    loc='upper left',
    frameon=True,
)

# --- PANEL D: Consumo Eléctrico vs Lodos Producidos ---
sns.scatterplot(
    data=df,
    x='energia_aeracion_kWh',
    y='lodos_generados_kg_d',
    hue='planta',
    palette=['#8E44AD', '#D35400', '#16A085'],
    s=80,
    alpha=0.85,
    ax=axes[1, 1],
)
axes[1, 1].set_title(
    'D) Energía de Aireación vs. Generación de Lodos',
    fontsize=12,
    fontweight='bold',
)
axes[1, 1].set_xlabel('Energía de Aireación (kWh)', fontweight='bold')
axes[1, 1].set_ylabel('Lodos Generados (kg/día)', fontweight='bold')
axes[1, 1].legend(title='Planta', loc='upper left', frameon=True)

plt.suptitle(
    'Dashboard de Desempeño Operacional y Calidad Ambiental — AquaLimpia S.A.',
    fontsize=15,
    fontweight='bold',
    y=1.02,
)
plt.tight_layout()
plt.savefig(
    'dashboard_exploratorio_aqualimpia.png', dpi=300, bbox_inches='tight'
)
plt.show()